In [4]:
import numpy as np

#List를 Numpy로 바꾸기
array = np.array([1,2,3])

print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소

3
int32
3


In [23]:
#Numpy 배열 초기화

#0부터 3까지의 배열 만들기
array1 = np.arange(4) 
array2 = np.zeros((4, 4), dtype=float) # 0으로 초기화(2차원 배열을 위해 4,4를 넣음)
array3 = np.ones((3, 3), dtype=str) # 1로 초기화
#0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3)) #0~9까지 3x3배열
#평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[1 5 6]
 [0 4 9]
 [8 6 0]]
[[ 0.55292935  1.59372082  0.80854621]
 [-0.40735162 -0.70719287  1.74024322]
 [ 0.81041475 -0.62347269  1.55485692]]


In [24]:
#배열 합치기
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2]) #concatenate='연결시키다'

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [41]:
#배열 형태 바꾸기
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2,2)) #위의 1차원을 2x2인 2차원 배열로 바꿔야 해서 [1,2],[3,4]
array3 = np.array([[1,2],[3,4]]) #array2와 같은 결과

print(array2.shape)
print(array2)
print(array3)

(2, 2)
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [66]:
#배열 세로 축으로 합치기
array1 = np.arange(4).reshape(1,4) # np.array[0,1,2,3].reshape(1,4)와 같은 결과
array2 = np.arange(8).reshape(2,4)

array3 = np.concatenate([array1, array2], axis=0)
print(array3.shape)
print(array1)
print(array2)
print(array3)
print("axis= ", np.sum(array2, axis=1))

(3, 4)
[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
axis=  [ 6 22]


In [68]:
#axis의 이해
array1 = np.arange(12).reshape(3,4)
print(array1.shape)
print(array1)

print("axis= 0:", np.sum(array1, axis=0)) #0은 행. 행 축을 기준으로 더하라는 뜻으로 각 행에 있는 열의 값을 더해서 하나로 만들면 된다.
print("axis= -2:", np.sum(array1, axis=-2))
print("axis= 1:", np.sum(array1, axis=1))
print("axis= -1: ", np.sum(array1, axis=-1))

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
axis= 0: [12 15 18 21]
axis= -2: [12 15 18 21]
axis= 1: [ 6 22 38]
axis= -1:  [ 6 22 38]


In [58]:
#배열 나누기
array = np.array([0,1,2,3,4,5,6,7]).reshape(2,4)
left, right = np.split(array, [2], axis=1) #[2]를 기준으로 세로로 왼쪽 오른쪽 자르는 듯..!(열 끼리의 연산..?)
print(left)
print(left.shape)
print(right)
print(right.shape)
print(right[1][1])
print(array)

[[0 1]
 [4 5]]
(2, 2)
[[2 3]
 [6 7]]
(2, 2)
7
[[0 1 2 3]
 [4 5 6 7]]


In [55]:
#배열 나누기2
array = np.array([0,1,2,3,4,5,6,7])
left, right = np.split(array, [2], axis=0) #이렇게 하면 [2]를 기준으로 가로로 자름
print(left)
print(left.shape)
print(right)
print(right.shape)
print(array)

[0 1]
(2,)
[2 3 4 5 6 7]
(6,)
[0 1 2 3 4 5 6 7]


In [11]:
#Numpy 연산(예를 곱셈으로 들었지만 연산은 모두 이와 같은 원리이다.)
array = np.random.randint(1,10,(2,2))
result_array = array * 10
print(array)
print(result_array)

[[6 9]
 [8 7]]
[[60 90]
 [80 70]]


In [12]:
#서로 다른 형태의 Numpy연산(행을 추가하는 경우)
array1 = np.arange(4).reshape(2,2) # (2x2)
array2 = np.arange(2) # (1x2)

array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


In [13]:
#서로 다른 형태의 Numpy연산(열을 추가하는 경우)
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(4).reshape(2,2)
array3 = np.concatenate([array1, array2], axis=0) # (4x2)
array4 = np.arange(0,4).reshape(4,1) # (4x1)

print(array3)
print(array4)
print(array3 + array4)

[[0 1]
 [2 3]
 [0 1]
 [2 3]]
[[0]
 [1]
 [2]
 [3]]
[[0 1]
 [3 4]
 [2 3]
 [5 6]]


In [16]:
#마스킹 연산
array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 < 10
print(array2)

#마스킹 연산의 응용
array1[array2] = 100 #array1중에서 10보다 작은 값만 값을 100으로 바꿔줄 수 있다.
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [17]:
#최대, 최소, 합계 평균값
array1 = np.arange(16).reshape(4,4)

print("최대값: ", np.max(array1))
print("최소값: ", np.min(array1))
print("합계: ", np.sum(array1))
print("평균값: ", np.mean(array1))

최대값:  15
최소값:  0
합계:  120
평균값:  7.5
